server:
  port: 8081
spring:
  cloud:     
    config:
      server:
        git:
          default-label: multiples-instances
          uri: https://github.com/JBFrank21/-sistema-educativo-microservicios
          search-paths: config-data
  application:
    name: config-service			